### PR TITLE
SP-11: Updated development gem dependencies

### PR DESCRIPTION
**Pull request by destinf**
Due to vulnerability in Nokogiri.
https://financeit.atlassian.net/browse/SP-11

### CODE REVIEW

**Comment by andyw8** [comment]
We might want to consider enabling Dependabot for this repo.

**Comment by destinf** [comment]
@dubroe Could you please review? Hopefully I'm not accidentally breaking anything.

**Comment by dubroe** [comment]
@destinf the code looks good. Could we QA the Financeit app pointing to this branch before we merge into master?

**Comment by destinf** [comment]
@dubroe Sounds good.

**Comment by destinf** [comment]
@dubroe Tests pass and QA tested. Can we merge?

**Comment by dubroe** [comment]
@destinf  oh we should probably update the gem version eh?

**Pull request merged**
